# Generated by Django 4.0.4 on 2022-05-31 22:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('text', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Qualite',
                'verbose_name_plural': 'Qualites',
            },
        ),
        migrations.AlterField(
            model_name='site',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
