# Generated by Django 4.0.4 on 2022-05-31 23:07

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_qualite_alter_site_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualite',
            name='description',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualite',
            name='icon',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
