# Generated by Django 4.0.4 on 2022-05-31 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_qualite_description_qualite_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualite',
            name='text',
            field=models.CharField(max_length=250),
        ),
    ]
